spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/contacts_app_db
    username: postgres
    password: Caligraf21540?
  jpa:
    database-platform: org.hibernate.dialect.PosgreSQLInnoDBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    throw-exception-if-no-handler-found: true
    async:
      request-timeout: 3600000
  # Disable open-in-view to prevent potential issues with lazy loading
  jpa.open-in-view: false
server:
  port: 8080
  error:
    path: /user/error
    whitelabel:
      enabled: false
